<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.continew.admin</groupId>
        <artifactId>continew-admin</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>continew-merchant</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>代理商、商户、KYC、审核与限额领域及应用服务</description>

    <dependencies>
        <dependency>
            <groupId>top.continew.admin</groupId>
            <artifactId>continew-common</artifactId>
        </dependency>
        <dependency>
            <groupId>top.continew.admin</groupId>
            <artifactId>continew-channel</artifactId>
        </dependency>
        <dependency>
            <groupId>top.continew.admin</groupId>
            <artifactId>continew-extension-workflow</artifactId>
        </dependency>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
