-- Phase-one schema rollback for empty test databases only. Never run for application rollback.
DROP TABLE IF EXISTS biz_channel_event;
DROP TABLE IF EXISTS biz_outbox_event;
DROP TABLE IF EXISTS biz_limit_adjustment;
DROP TABLE IF EXISTS biz_workflow_instance;
DROP TABLE IF EXISTS biz_review_record;
DROP TABLE IF EXISTS biz_agent_pricing_version;
DROP TABLE IF EXISTS biz_kyc_attachment;
DROP TABLE IF EXISTS biz_kyc_version;
DROP TABLE IF EXISTS biz_onboarding_application;
DROP TABLE IF EXISTS biz_merchant;
DROP TABLE IF EXISTS biz_agent_closure;
DROP TABLE IF EXISTS biz_agent;

-- Flowable 7.1.0.2 official rollback: engine -> history -> common.
drop index ACT_IDX_EXEC_BUSKEY on ACT_RU_EXECUTION;
drop index ACT_IDX_VARIABLE_TASK_ID on ACT_RU_VARIABLE;
drop index ACT_IDX_INFO_PROCDEF on ACT_PROCDEF_INFO;

alter table ACT_GE_BYTEARRAY
    drop FOREIGN KEY ACT_FK_BYTEARR_DEPL;

alter table ACT_RU_EXECUTION
    drop FOREIGN KEY ACT_FK_EXE_PROCINST;

alter table ACT_RU_EXECUTION
    drop FOREIGN KEY ACT_FK_EXE_PARENT;

alter table ACT_RU_EXECUTION
    drop FOREIGN KEY ACT_FK_EXE_SUPER;

alter table ACT_RU_EXECUTION
    drop FOREIGN KEY ACT_FK_EXE_PROCDEF;

alter table ACT_RU_IDENTITYLINK
    drop FOREIGN KEY ACT_FK_TSKASS_TASK;

alter table ACT_RU_IDENTITYLINK
    drop FOREIGN KEY ACT_FK_IDL_PROCINST;

alter table ACT_RU_IDENTITYLINK
    drop FOREIGN KEY ACT_FK_ATHRZ_PROCEDEF;

alter table ACT_RU_TASK
	drop FOREIGN KEY ACT_FK_TASK_EXE;

alter table ACT_RU_TASK
	drop FOREIGN KEY ACT_FK_TASK_PROCINST;

alter table ACT_RU_TASK
	drop FOREIGN KEY ACT_FK_TASK_PROCDEF;

alter table ACT_RU_VARIABLE
    drop FOREIGN KEY ACT_FK_VAR_EXE;

alter table ACT_RU_VARIABLE
	drop FOREIGN KEY ACT_FK_VAR_PROCINST;

alter table ACT_RU_JOB
    drop FOREIGN KEY ACT_FK_JOB_EXECUTION;

alter table ACT_RU_JOB
    drop foreign key ACT_FK_JOB_PROCESS_INSTANCE;

alter table ACT_RU_JOB
    drop foreign key ACT_FK_JOB_PROC_DEF;

alter table ACT_RU_TIMER_JOB
    drop foreign key ACT_FK_TIMER_JOB_EXECUTION;

alter table ACT_RU_TIMER_JOB
    drop foreign key ACT_FK_TIMER_JOB_PROCESS_INSTANCE;

alter table ACT_RU_TIMER_JOB
    drop foreign key ACT_FK_TIMER_JOB_PROC_DEF;

alter table ACT_RU_SUSPENDED_JOB
    drop foreign key ACT_FK_SUSPENDED_JOB_EXECUTION;

alter table ACT_RU_SUSPENDED_JOB
    drop foreign key ACT_FK_SUSPENDED_JOB_PROCESS_INSTANCE;

alter table ACT_RU_SUSPENDED_JOB
    drop foreign key ACT_FK_SUSPENDED_JOB_PROC_DEF;

alter table ACT_RU_DEADLETTER_JOB
    drop foreign key ACT_FK_DEADLETTER_JOB_EXECUTION;

alter table ACT_RU_DEADLETTER_JOB
    drop foreign key ACT_FK_DEADLETTER_JOB_PROCESS_INSTANCE;

alter table ACT_RU_DEADLETTER_JOB
    drop foreign key ACT_FK_DEADLETTER_JOB_PROC_DEF;

alter table ACT_RU_EVENT_SUBSCR
    drop FOREIGN KEY ACT_FK_EVENT_EXEC;

alter table ACT_RE_MODEL
    drop FOREIGN KEY ACT_FK_MODEL_SOURCE;

alter table ACT_RE_MODEL
    drop FOREIGN KEY ACT_FK_MODEL_SOURCE_EXTRA;

alter table ACT_RE_MODEL
    drop FOREIGN KEY ACT_FK_MODEL_DEPLOYMENT;

alter table ACT_PROCDEF_INFO
    drop FOREIGN KEY ACT_FK_INFO_JSON_BA;

alter table ACT_PROCDEF_INFO
    drop FOREIGN KEY ACT_FK_INFO_PROCDEF;

drop index ACT_IDX_ATHRZ_PROCEDEF on ACT_RU_IDENTITYLINK;

drop index ACT_IDX_RU_ACTI_START on ACT_RU_ACTINST;
drop index ACT_IDX_RU_ACTI_END on ACT_RU_ACTINST;
drop index ACT_IDX_RU_ACTI_PROC on ACT_RU_ACTINST;
drop index ACT_IDX_RU_ACTI_PROC_ACT on ACT_RU_ACTINST;
drop index ACT_IDX_RU_ACTI_EXEC on ACT_RU_ACTINST;
drop index ACT_IDX_RU_ACTI_EXEC_ACT on ACT_RU_ACTINST;

drop table if exists ACT_RU_ACTINST;
drop table if exists ACT_RE_DEPLOYMENT;
drop table if exists ACT_RE_MODEL;
drop table if exists ACT_RE_PROCDEF;
drop table if exists ACT_RU_EXECUTION;
drop table if exists ACT_EVT_LOG;
drop table if exists ACT_PROCDEF_INFO;

drop index ACT_IDX_HI_PRO_INST_END on ACT_HI_PROCINST;
drop index ACT_IDX_HI_PRO_I_BUSKEY on ACT_HI_PROCINST;
drop index ACT_IDX_HI_ACT_INST_START on ACT_HI_ACTINST;
drop index ACT_IDX_HI_ACT_INST_END on ACT_HI_ACTINST;
drop index ACT_IDX_HI_DETAIL_PROC_INST on ACT_HI_DETAIL;
drop index ACT_IDX_HI_DETAIL_ACT_INST on ACT_HI_DETAIL;
drop index ACT_IDX_HI_DETAIL_TIME on ACT_HI_DETAIL;
drop index ACT_IDX_HI_DETAIL_NAME on ACT_HI_DETAIL;
drop index ACT_IDX_HI_DETAIL_TASK_ID on ACT_HI_DETAIL;
drop index ACT_IDX_HI_PROCVAR_PROC_INST on ACT_HI_VARINST;
drop index ACT_IDX_HI_PROCVAR_TASK_ID on ACT_HI_VARINST;
drop index ACT_IDX_HI_PROCVAR_EXE on ACT_HI_VARINST;
drop index ACT_IDX_HI_ACT_INST_PROCINST on ACT_HI_ACTINST;
drop index ACT_IDX_HI_IDENT_LNK_TASK on ACT_HI_IDENTITYLINK;
drop index ACT_IDX_HI_IDENT_LNK_PROCINST on ACT_HI_IDENTITYLINK;
drop index ACT_IDX_HI_TASK_INST_PROCINST on ACT_HI_TASKINST;

drop table if exists ACT_HI_PROCINST;
drop table if exists ACT_HI_ACTINST;
drop table if exists ACT_HI_DETAIL;
drop table if exists ACT_HI_COMMENT;
drop table if exists ACT_HI_ATTACHMENT;


alter table FLW_RU_BATCH_PART
    drop foreign key FLW_FK_BATCH_PART_PARENT;

drop index FLW_IDX_BATCH_PART on FLW_RU_BATCH_PART;

drop table if exists FLW_RU_BATCH_PART;
drop table if exists FLW_RU_BATCH;

drop index ACT_IDX_ENT_LNK_SCOPE on ACT_RU_ENTITYLINK;
drop index ACT_IDX_ENT_LNK_REF_SCOPE on ACT_RU_ENTITYLINK;
drop index ACT_IDX_ENT_LNK_ROOT_SCOPE on ACT_RU_ENTITYLINK;
drop index ACT_IDX_ENT_LNK_SCOPE_DEF on ACT_RU_ENTITYLINK;

drop table if exists ACT_RU_ENTITYLINK;

drop index ACT_IDX_HI_ENT_LNK_SCOPE on ACT_HI_ENTITYLINK;
drop index ACT_IDX_HI_ENT_LNK_REF_SCOPE on ACT_HI_ENTITYLINK;
drop index ACT_IDX_HI_ENT_LNK_ROOT_SCOPE on ACT_HI_ENTITYLINK;
drop index ACT_IDX_HI_ENT_LNK_SCOPE_DEF on ACT_HI_ENTITYLINK;

drop table if exists ACT_HI_ENTITYLINK;

drop index ACT_IDX_EVENT_SUBSCR_CONFIG_ on ACT_RU_EVENT_SUBSCR;
drop index ACT_IDX_EVENT_SUBSCR_EXEC_ID on ACT_RU_EVENT_SUBSCR;
drop index ACT_IDX_EVENT_SUBSCR_PROC_ID on ACT_RU_EVENT_SUBSCR;
drop index ACT_IDX_EVENT_SUBSCR_SCOPEREF_ on ACT_RU_EVENT_SUBSCR;

drop table if exists ACT_RU_EVENT_SUBSCR;

drop index ACT_IDX_IDENT_LNK_USER on ACT_RU_IDENTITYLINK;
drop index ACT_IDX_IDENT_LNK_GROUP on ACT_RU_IDENTITYLINK;
drop index ACT_IDX_IDENT_LNK_SCOPE on ACT_RU_IDENTITYLINK;
drop index ACT_IDX_IDENT_LNK_SUB_SCOPE on ACT_RU_IDENTITYLINK;
drop index ACT_IDX_IDENT_LNK_SCOPE_DEF on ACT_RU_IDENTITYLINK;

drop table if exists ACT_RU_IDENTITYLINK;

drop index ACT_IDX_HI_IDENT_LNK_USER on ACT_HI_IDENTITYLINK;
drop index ACT_IDX_HI_IDENT_LNK_SCOPE on ACT_HI_IDENTITYLINK;
drop index ACT_IDX_HI_IDENT_LNK_SUB_SCOPE on ACT_HI_IDENTITYLINK;
drop index ACT_IDX_HI_IDENT_LNK_SCOPE_DEF on ACT_HI_IDENTITYLINK;

drop table if exists ACT_HI_IDENTITYLINK;

alter table ACT_RU_JOB
    drop foreign key ACT_FK_JOB_EXCEPTION;

alter table ACT_RU_JOB
    drop foreign key ACT_FK_JOB_CUSTOM_VALUES;

alter table ACT_RU_TIMER_JOB
    drop foreign key ACT_FK_TIMER_JOB_EXCEPTION;

alter table ACT_RU_TIMER_JOB
    drop foreign key ACT_FK_TIMER_JOB_CUSTOM_VALUES;

alter table ACT_RU_SUSPENDED_JOB
    drop foreign key ACT_FK_SUSPENDED_JOB_EXCEPTION;

alter table ACT_RU_SUSPENDED_JOB
    drop foreign key ACT_FK_SUSPENDED_JOB_CUSTOM_VALUES;

alter table ACT_RU_DEADLETTER_JOB
    drop foreign key ACT_FK_DEADLETTER_JOB_EXCEPTION;

alter table ACT_RU_DEADLETTER_JOB
    drop foreign key ACT_FK_DEADLETTER_JOB_CUSTOM_VALUES;

alter table ACT_RU_EXTERNAL_JOB
    drop foreign key ACT_FK_EXTERNAL_JOB_EXCEPTION;

alter table ACT_RU_EXTERNAL_JOB
    drop foreign key ACT_FK_EXTERNAL_JOB_CUSTOM_VALUES;

drop index ACT_IDX_JOB_EXCEPTION_STACK_ID on ACT_RU_JOB;
drop index ACT_IDX_JOB_CUSTOM_VALUES_ID on ACT_RU_JOB;
drop index ACT_IDX_JOB_CORRELATION_ID on ACT_RU_JOB;
drop index ACT_IDX_JOB_SCOPE on ACT_RU_JOB;
drop index ACT_IDX_JOB_SUB_SCOPE on ACT_RU_JOB;
drop index ACT_IDX_JOB_SCOPE_DEF on ACT_RU_JOB;

drop index ACT_IDX_TIMER_JOB_EXCEPTION_STACK_ID on ACT_RU_TIMER_JOB;
drop index ACT_IDX_TIMER_JOB_CUSTOM_VALUES_ID on ACT_RU_TIMER_JOB;
drop index ACT_IDX_TIMER_JOB_CORRELATION_ID on ACT_RU_TIMER_JOB;
drop index ACT_IDX_TIMER_JOB_DUEDATE on ACT_RU_TIMER_JOB;
drop index ACT_IDX_TJOB_SCOPE on ACT_RU_TIMER_JOB;
drop index ACT_IDX_TJOB_SUB_SCOPE on ACT_RU_TIMER_JOB;
drop index ACT_IDX_TJOB_SCOPE_DEF on ACT_RU_TIMER_JOB;

drop index ACT_IDX_SUSPENDED_JOB_EXCEPTION_STACK_ID on ACT_RU_SUSPENDED_JOB;
drop index ACT_IDX_SUSPENDED_JOB_CUSTOM_VALUES_ID on ACT_RU_SUSPENDED_JOB;
drop index ACT_IDX_SUSPENDED_JOB_CORRELATION_ID on ACT_RU_SUSPENDED_JOB;
drop index ACT_IDX_SJOB_SCOPE on ACT_RU_SUSPENDED_JOB;
drop index ACT_IDX_SJOB_SUB_SCOPE on ACT_RU_SUSPENDED_JOB;
drop index ACT_IDX_SJOB_SCOPE_DEF on ACT_RU_SUSPENDED_JOB;

drop index ACT_IDX_DEADLETTER_JOB_EXCEPTION_STACK_ID on ACT_RU_DEADLETTER_JOB;
drop index ACT_IDX_DEADLETTER_JOB_CUSTOM_VALUES_ID on ACT_RU_DEADLETTER_JOB;
drop index ACT_IDX_DEADLETTER_JOB_CORRELATION_ID on ACT_RU_DEADLETTER_JOB;
drop index ACT_IDX_DJOB_SCOPE on ACT_RU_DEADLETTER_JOB;
drop index ACT_IDX_DJOB_SUB_SCOPE on ACT_RU_DEADLETTER_JOB;
drop index ACT_IDX_DJOB_SCOPE_DEF on ACT_RU_DEADLETTER_JOB;

drop index ACT_IDX_EXTERNAL_JOB_EXCEPTION_STACK_ID on ACT_RU_EXTERNAL_JOB;
drop index ACT_IDX_EXTERNAL_JOB_CUSTOM_VALUES_ID on ACT_RU_EXTERNAL_JOB;
drop index ACT_IDX_EXTERNAL_JOB_CORRELATION_ID on ACT_RU_EXTERNAL_JOB;
drop index ACT_IDX_EJOB_SCOPE on ACT_RU_EXTERNAL_JOB;
drop index ACT_IDX_EJOB_SUB_SCOPE on ACT_RU_EXTERNAL_JOB;
drop index ACT_IDX_EJOB_SCOPE_DEF on ACT_RU_EXTERNAL_JOB;

drop table if exists ACT_RU_JOB;
drop table if exists ACT_RU_TIMER_JOB;
drop table if exists ACT_RU_SUSPENDED_JOB;
drop table if exists ACT_RU_DEADLETTER_JOB;
drop table if exists ACT_RU_HISTORY_JOB;
drop table if exists ACT_RU_EXTERNAL_JOB;

drop index ACT_IDX_TASK_CREATE on ACT_RU_TASK;
drop index ACT_IDX_TASK_SCOPE on ACT_RU_TASK;
drop index ACT_IDX_TASK_SUB_SCOPE on ACT_RU_TASK;
drop index ACT_IDX_TASK_SCOPE_DEF on ACT_RU_TASK;

drop table if exists ACT_RU_TASK;

drop index ACT_IDX_ACT_HI_TSK_LOG_TASK on ACT_HI_TSK_LOG;

drop table if exists ACT_HI_TSK_LOG;

drop index ACT_IDX_HI_TASK_SCOPE on ACT_HI_TASKINST;
drop index ACT_IDX_HI_TASK_SUB_SCOPE on ACT_HI_TASKINST;
drop index ACT_IDX_HI_TASK_SCOPE_DEF on ACT_HI_TASKINST;

drop table if exists ACT_HI_TASKINST;

alter table ACT_RU_VARIABLE
    drop FOREIGN KEY ACT_FK_VAR_BYTEARRAY;

drop index ACT_IDX_RU_VAR_SCOPE_ID_TYPE on ACT_RU_VARIABLE;
drop index ACT_IDX_RU_VAR_SUB_ID_TYPE on ACT_RU_VARIABLE;

drop table if exists ACT_RU_VARIABLE;

drop index ACT_IDX_HI_PROCVAR_NAME_TYPE on ACT_HI_VARINST;
drop index ACT_IDX_HI_VAR_SCOPE_ID_TYPE on ACT_HI_VARINST;
drop index ACT_IDX_HI_VAR_SUB_ID_TYPE on ACT_HI_VARINST;

drop table if exists ACT_HI_VARINST;


drop table if exists ACT_GE_BYTEARRAY;
drop table if exists ACT_GE_PROPERTY;
